spring.profiles.active: local
#spring:
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    protocol: smtp
#    default-encoding: utf-8
#    username: i3rewmaster@gmail.com
#    password: gooracle11G!@#$


---
spring:
  profiles: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  batch:
    schema: classpath:/org/springframework/batch/core/schema-h2.sql
    initialize-schema: always
#    job:
#      names: parentJob
  h2:
    console:
      enabled: true
---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learning_spring_batch
    username: root
    password: 1234
  batch:
    schema: classpath:/org/springframework/batch/core/schema-mysql.sql
    initialize-schema: always
    job:
      names: parentJob