spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learning_spring_batch
    username: root
    password: 1234
  batch:
    schema: classpath:/org/springframework/batch/core/schema-mysql.sql
    initialize-schema: always
